import type { Chapter, ResourceId } from '../types';
import { Material } from '../voxels';

/**
 * Каталог зданий (§6 ТЗ) — данные, не код.
 *
 * Новое здание это запись в этом файле и ничего больше: ни правок логики, ни ветвлений
 * по идентификаторам где-либо ещё. Форма тоже данные — список коробок, а не код на здание.
 */

export type BuildingCategory = 'home' | 'gather' | 'craft' | 'utility' | 'culture' | 'decor';

/** Чем занимается работник. По нему подбирается подходящая черта характера. */
export type JobType =
  'wood' | 'stone' | 'clay' | 'sand' | 'fish' | 'forage' | 'farm' | 'craft' | 'care';

/** Коробка воксельной формы. Смещение от угла участка, размеры в вокселях. */
export interface ShapeBox {
  x: number;
  y: number;
  z: number;
  w: number;
  h: number;
  d: number;
  mat: number;
}

export interface BuildingType {
  id: string;
  name: string;
  category: BuildingCategory;
  cost: Partial<Record<ResourceId, number>>;
  /** Сколько тиков занимает стройка при одном строителе. */
  buildTicks: number;
  footprint: { w: number; d: number };
  /** Сколько человек может здесь работать. Ноль — работать негде. */
  workers: number;
  jobType?: JobType;
  /** Что производит за тик при полной эффективности. */
  output?: Partial<Record<ResourceId, number>>;
  /** Что потребляет за тик. */
  input?: Partial<Record<ResourceId, number>>;
  /** Сколько жителей может здесь ночевать. */
  beds?: number;
  /** Прибавка к вместимости склада. */
  storage?: number;
  /** Ставится над водой: пирс и мост иначе некуда деть. */
  overWater?: boolean;
  comfortRadius: number;
  comfortValue: number;
  requires: readonly string[];
  unlockChapter: Chapter;
  description: string;
  shape: readonly ShapeBox[];
}

// --- Заготовки форм --------------------------------------------------------

/** Коробка со стенами, полом и плоской крышей. */
function hollowBox(w: number, d: number, h: number, wall: number, roof: number): ShapeBox[] {
  return [
    { x: 0, y: 0, z: 0, w, h: 1, d, mat: Material.PLANK },
    { x: 0, y: 1, z: 0, w, h: h - 1, d: 1, mat: wall },
    { x: 0, y: 1, z: d - 1, w, h: h - 1, d: 1, mat: wall },
    { x: 0, y: 1, z: 1, w: 1, h: h - 1, d: d - 2, mat: wall },
    { x: w - 1, y: 1, z: 1, w: 1, h: h - 1, d: d - 2, mat: wall },
    { x: 0, y: h, z: 0, w, h: 1, d, mat: roof },
  ];
}

/** Навес: четыре столба и крыша. Так выглядит всё, что работает под открытым небом. */
function shelter(w: number, d: number, h: number, roof: number): ShapeBox[] {
  return [
    { x: 0, y: 0, z: 0, w: 1, h, d: 1, mat: Material.WOOD },
    { x: w - 1, y: 0, z: 0, w: 1, h, d: 1, mat: Material.WOOD },
    { x: 0, y: 0, z: d - 1, w: 1, h, d: 1, mat: Material.WOOD },
    { x: w - 1, y: 0, z: d - 1, w: 1, h, d: 1, mat: Material.WOOD },
    { x: 0, y: h, z: 0, w, h: 1, d, mat: roof },
  ];
}

/** Низкая площадка: скамейки, клумбы, площади. */
function platform(w: number, d: number, mat: number): ShapeBox[] {
  return [{ x: 0, y: 0, z: 0, w, h: 1, d, mat }];
}

// --- Каталог ---------------------------------------------------------------

const NO_REQUIREMENTS: readonly string[] = [];

export const BUILDINGS: readonly BuildingType[] = [
  // Жильё
  {
    id: 'hut',
    name: 'Шалаш',
    category: 'home',
    cost: { wood: 4 },
    buildTicks: 6,
    footprint: { w: 2, d: 2 },
    workers: 0,
    beds: 1,
    comfortRadius: 4,
    comfortValue: 2,
    requires: NO_REQUIREMENTS,
    unlockChapter: 1,
    description: 'Крыша над головой на первое время',
    shape: shelter(2, 2, 2, Material.THATCH),
  },
  {
    id: 'cottage',
    name: 'Домик',
    category: 'home',
    cost: { plank: 12, stone: 6 },
    buildTicks: 16,
    footprint: { w: 3, d: 3 },
    workers: 0,
    beds: 2,
    comfortRadius: 6,
    comfortValue: 5,
    requires: ['sawmill'],
    unlockChapter: 1,
    description: 'Настоящий дом на двоих',
    shape: hollowBox(3, 3, 3, Material.PLANK, Material.THATCH),
  },
  {
    id: 'cliff_house',
    name: 'Дом у скалы',
    category: 'home',
    cost: { plank: 20, brick: 12, glass: 4 },
    buildTicks: 26,
    footprint: { w: 4, d: 3 },
    workers: 0,
    beds: 2,
    comfortRadius: 7,
    comfortValue: 8,
    requires: ['kiln'],
    unlockChapter: 3,
    description: 'Тёплый дом с окнами на море',
    shape: hollowBox(4, 3, 4, Material.BRICK, Material.PLANK),
  },
  {
    id: 'commons',
    name: 'Общий дом',
    category: 'home',
    cost: { plank: 30, cloth: 10 },
    buildTicks: 32,
    footprint: { w: 5, d: 4 },
    workers: 0,
    beds: 4,
    comfortRadius: 9,
    comfortValue: 10,
    requires: ['loom'],
    unlockChapter: 2,
    description: 'Четверо под одной крышей, и всем есть с кем поговорить',
    shape: hollowBox(5, 4, 3, Material.PLANK, Material.THATCH),
  },

  // Добыча
  {
    id: 'woodcutter',
    name: 'Место дровосека',
    category: 'gather',
    cost: { wood: 6 },
    buildTicks: 8,
    footprint: { w: 2, d: 2 },
    workers: 1,
    jobType: 'wood',
    output: { wood: 1.2 },
    comfortRadius: 0,
    comfortValue: 0,
    requires: NO_REQUIREMENTS,
    unlockChapter: 1,
    description: 'Отсюда приносят дерево',
    shape: shelter(2, 2, 2, Material.PLANK),
  },
  {
    id: 'quarry',
    name: 'Каменоломня',
    category: 'gather',
    cost: { wood: 12 },
    buildTicks: 12,
    footprint: { w: 3, d: 3 },
    workers: 2,
    jobType: 'stone',
    output: { stone: 1 },
    comfortRadius: 0,
    comfortValue: 0,
    requires: NO_REQUIREMENTS,
    unlockChapter: 1,
    description: 'Камень из скалы',
    shape: shelter(3, 3, 2, Material.STONE),
  },
  {
    id: 'clay_pit',
    name: 'Глиняный карьер',
    category: 'gather',
    cost: { wood: 6 },
    buildTicks: 10,
    footprint: { w: 2, d: 2 },
    workers: 1,
    jobType: 'clay',
    output: { clay: 1 },
    comfortRadius: 0,
    comfortValue: 0,
    requires: NO_REQUIREMENTS,
    unlockChapter: 1,
    description: 'Глина у воды',
    shape: shelter(2, 2, 2, Material.CLAY),
  },
  {
    id: 'sand_pit',
    name: 'Песчаная яма',
    category: 'gather',
    cost: { wood: 5 },
    buildTicks: 8,
    footprint: { w: 2, d: 2 },
    workers: 1,
    jobType: 'sand',
    output: { sand: 1.2 },
    comfortRadius: 0,
    comfortValue: 0,
    requires: NO_REQUIREMENTS,
    unlockChapter: 2,
    description: 'Песок с пляжа',
    shape: shelter(2, 2, 2, Material.SAND),
  },
  {
    id: 'pier',
    name: 'Рыбацкий пирс',
    category: 'gather',
    cost: { plank: 10 },
    buildTicks: 14,
    footprint: { w: 2, d: 4 },
    workers: 2,
    jobType: 'fish',
    output: { fish: 1 },
    overWater: true,
    comfortRadius: 4,
    comfortValue: 3,
    requires: NO_REQUIREMENTS,
    unlockChapter: 1,
    description: 'Помост над водой, с него ловят рыбу',
    shape: platform(2, 4, Material.PLANK),
  },
  {
    id: 'berry_patch',
    name: 'Ягодник',
    category: 'gather',
    cost: { wood: 4 },
    buildTicks: 6,
    footprint: { w: 3, d: 3 },
    workers: 1,
    jobType: 'forage',
    output: { fruit: 1 },
    comfortRadius: 3,
    comfortValue: 2,
    requires: NO_REQUIREMENTS,
    unlockChapter: 1,
    description: 'Ухоженные кусты дают больше ягод',
    shape: platform(3, 3, Material.LEAVES),
  },
  {
    id: 'field',
    name: 'Поле',
    category: 'gather',
    cost: { wood: 6 },
    buildTicks: 12,
    footprint: { w: 4, d: 4 },
    workers: 2,
    jobType: 'farm',
    output: { grain: 1.2 },
    comfortRadius: 3,
    comfortValue: 2,
    requires: NO_REQUIREMENTS,
    unlockChapter: 2,
    description: 'Зерно на хлеб',
    shape: platform(4, 4, Material.DIRT),
  },
  {
    id: 'pen',
    name: 'Загон',
    category: 'gather',
    cost: { plank: 10 },
    buildTicks: 14,
    footprint: { w: 4, d: 4 },
    workers: 1,
    jobType: 'care',
    output: { wool: 0.6 },
    comfortRadius: 3,
    comfortValue: 1,
    requires: NO_REQUIREMENTS,
    unlockChapter: 2,
    description: 'Шерсть и спокойное блеяние',
    shape: platform(4, 4, Material.GRASS),
  },
  {
    id: 'fiber_patch',
    name: 'Грядка волокна',
    category: 'gather',
    cost: { wood: 4 },
    buildTicks: 8,
    footprint: { w: 3, d: 3 },
    workers: 1,
    jobType: 'farm',
    output: { fiber: 1 },
    comfortRadius: 2,
    comfortValue: 1,
    requires: NO_REQUIREMENTS,
    unlockChapter: 2,
    description: 'Из него получается ткань',
    shape: platform(3, 3, Material.GRASS),
  },

  // Переработка
  {
    id: 'sawmill',
    name: 'Лесопилка',
    category: 'craft',
    // Только дерево: иначе первая же цепочка замыкается в круг — лесопилке нужен камень,
    // каменоломне доски, а доски делает лесопилка.
    cost: { wood: 14 },
    buildTicks: 16,
    footprint: { w: 3, d: 3 },
    workers: 2,
    jobType: 'craft',
    input: { wood: 2 },
    output: { plank: 1 },
    comfortRadius: 0,
    comfortValue: 0,
    requires: NO_REQUIREMENTS,
    unlockChapter: 1,
    description: 'Превращает брёвна в доски',
    shape: hollowBox(3, 3, 2, Material.WOOD, Material.PLANK),
  },
  {
    id: 'kiln',
    name: 'Печь для кирпича',
    category: 'craft',
    cost: { stone: 14, clay: 6 },
    buildTicks: 20,
    footprint: { w: 3, d: 3 },
    workers: 1,
    jobType: 'craft',
    input: { clay: 2 },
    output: { brick: 1 },
    comfortRadius: 0,
    comfortValue: 0,
    requires: ['sawmill'],
    unlockChapter: 2,
    description: 'Обжигает глину до кирпича',
    shape: hollowBox(3, 3, 3, Material.BRICK, Material.STONE),
  },
  {
    id: 'glassworks',
    name: 'Стеклодувная',
    category: 'craft',
    cost: { brick: 12, plank: 8 },
    buildTicks: 22,
    footprint: { w: 3, d: 3 },
    workers: 1,
    jobType: 'craft',
    input: { sand: 3 },
    output: { glass: 1 },
    comfortRadius: 0,
    comfortValue: 0,
    requires: ['kiln'],
    unlockChapter: 3,
    description: 'Из песка получается стекло',
    shape: hollowBox(3, 3, 3, Material.BRICK, Material.GLASS),
  },
  {
    id: 'loom',
    name: 'Ткацкая',
    category: 'craft',
    cost: { plank: 14, stone: 4 },
    buildTicks: 20,
    footprint: { w: 3, d: 3 },
    workers: 2,
    jobType: 'craft',
    input: { fiber: 2, wool: 1 },
    output: { cloth: 1 },
    comfortRadius: 0,
    comfortValue: 0,
    requires: ['sawmill'],
    unlockChapter: 3,
    description: 'Волокно и шерсть становятся тканью',
    shape: hollowBox(3, 3, 3, Material.PLANK, Material.THATCH),
  },
  {
    id: 'bakery',
    name: 'Пекарня',
    category: 'craft',
    cost: { brick: 10, plank: 8 },
    buildTicks: 20,
    footprint: { w: 3, d: 3 },
    workers: 1,
    jobType: 'craft',
    input: { grain: 3 },
    output: { bread: 2 },
    comfortRadius: 5,
    comfortValue: 4,
    requires: ['kiln'],
    unlockChapter: 2,
    description: 'Пахнет так, что слышно с другого конца острова',
    shape: hollowBox(3, 3, 3, Material.BRICK, Material.THATCH),
  },
  {
    id: 'workshop',
    name: 'Мастерская',
    category: 'craft',
    cost: { plank: 16, stone: 8 },
    buildTicks: 24,
    footprint: { w: 3, d: 3 },
    workers: 2,
    jobType: 'craft',
    input: { plank: 1, stone: 1 },
    output: { tool: 1 },
    comfortRadius: 0,
    comfortValue: 0,
    requires: ['sawmill'],
    unlockChapter: 2,
    description: 'Инструменты, без которых дальше не пойдёт',
    shape: hollowBox(3, 3, 3, Material.PLANK, Material.STONE),
  },
  {
    id: 'kitchen',
    name: 'Кухня',
    category: 'craft',
    cost: { plank: 12, brick: 6 },
    buildTicks: 18,
    footprint: { w: 3, d: 3 },
    workers: 2,
    jobType: 'craft',
    input: { fish: 1, fruit: 1 },
    output: { meal: 2 },
    comfortRadius: 6,
    comfortValue: 5,
    requires: ['sawmill'],
    unlockChapter: 2,
    description: 'Здесь готовят обед на всех',
    shape: hollowBox(3, 3, 3, Material.PLANK, Material.BRICK),
  },

  // Быт
  {
    id: 'well',
    name: 'Колодец',
    category: 'utility',
    cost: { stone: 10 },
    buildTicks: 12,
    footprint: { w: 2, d: 2 },
    workers: 0,
    comfortRadius: 8,
    comfortValue: 6,
    requires: NO_REQUIREMENTS,
    unlockChapter: 1,
    description: 'Чистая вода рядом с домом',
    shape: platform(2, 2, Material.STONE),
  },
  {
    id: 'granary',
    name: 'Амбар',
    category: 'utility',
    cost: { plank: 16, stone: 6 },
    buildTicks: 20,
    footprint: { w: 3, d: 3 },
    workers: 0,
    storage: 150,
    comfortRadius: 0,
    comfortValue: 0,
    requires: ['sawmill'],
    unlockChapter: 2,
    description: 'Плюс сто пятьдесят к складу',
    shape: hollowBox(3, 3, 3, Material.PLANK, Material.THATCH),
  },
  {
    id: 'cellar',
    name: 'Погреб',
    category: 'utility',
    cost: { stone: 12, plank: 6 },
    buildTicks: 18,
    footprint: { w: 2, d: 3 },
    workers: 0,
    storage: 100,
    comfortRadius: 0,
    comfortValue: 0,
    requires: NO_REQUIREMENTS,
    unlockChapter: 2,
    description: 'Прохладно и сухо',
    shape: platform(2, 3, Material.STONE),
  },
  {
    id: 'firepit',
    name: 'Костровище',
    category: 'utility',
    cost: { stone: 6, wood: 4 },
    buildTicks: 8,
    footprint: { w: 3, d: 3 },
    workers: 0,
    comfortRadius: 10,
    comfortValue: 9,
    requires: NO_REQUIREMENTS,
    unlockChapter: 1,
    description: 'Вечером здесь собираются все',
    shape: platform(3, 3, Material.STONE),
  },
  {
    id: 'bathhouse',
    name: 'Баня',
    category: 'utility',
    cost: { plank: 18, stone: 10 },
    buildTicks: 24,
    footprint: { w: 3, d: 3 },
    workers: 0,
    comfortRadius: 7,
    comfortValue: 7,
    requires: ['sawmill'],
    unlockChapter: 3,
    description: 'Тепло и пар',
    shape: hollowBox(3, 3, 3, Material.PLANK, Material.STONE),
  },
  {
    id: 'lamp',
    name: 'Фонарь',
    category: 'utility',
    cost: { wood: 3, glass: 1 },
    buildTicks: 4,
    footprint: { w: 1, d: 1 },
    workers: 0,
    comfortRadius: 6,
    comfortValue: 4,
    requires: NO_REQUIREMENTS,
    unlockChapter: 2,
    description: 'Вечером под ним светло',
    shape: [
      { x: 0, y: 0, z: 0, w: 1, h: 3, d: 1, mat: Material.WOOD },
      { x: 0, y: 3, z: 0, w: 1, h: 1, d: 1, mat: Material.GLASS },
    ],
  },
  {
    id: 'harbor',
    name: 'Порт',
    category: 'utility',
    cost: { plank: 30, stone: 20, tool: 4 },
    buildTicks: 30,
    footprint: { w: 4, d: 4 },
    workers: 1,
    jobType: 'craft',
    storage: 100,
    overWater: true,
    comfortRadius: 8,
    comfortValue: 6,
    requires: ['workshop'],
    unlockChapter: 5,
    description: 'Отсюда виден весь мир, и сюда приходят лодки',
    shape: [
      { x: 0, y: 0, z: 0, w: 4, h: 1, d: 4, mat: Material.PLANK },
      { x: 0, y: 1, z: 0, w: 1, h: 4, d: 1, mat: Material.WOOD },
      { x: 3, y: 1, z: 3, w: 1, h: 4, d: 1, mat: Material.WOOD },
      { x: 0, y: 5, z: 0, w: 4, h: 1, d: 4, mat: Material.THATCH },
    ],
  },
  {
    id: 'bridge',
    name: 'Мост',
    category: 'utility',
    cost: { plank: 8 },
    buildTicks: 10,
    footprint: { w: 2, d: 4 },
    workers: 0,
    overWater: true,
    comfortRadius: 0,
    comfortValue: 0,
    requires: ['sawmill'],
    unlockChapter: 3,
    description: 'Через воду посуху',
    shape: platform(2, 4, Material.PLANK),
  },

  // Культура и уют
  {
    id: 'bench',
    name: 'Скамейка',
    category: 'culture',
    cost: { plank: 3 },
    buildTicks: 3,
    footprint: { w: 2, d: 1 },
    workers: 0,
    comfortRadius: 5,
    comfortValue: 4,
    requires: NO_REQUIREMENTS,
    unlockChapter: 1,
    description: 'Место, чтобы посидеть и посмотреть',
    shape: [
      { x: 0, y: 0, z: 0, w: 2, h: 1, d: 1, mat: Material.PLANK },
      { x: 0, y: 1, z: 0, w: 2, h: 1, d: 1, mat: Material.WOOD },
    ],
  },
  {
    id: 'square',
    name: 'Площадь',
    category: 'culture',
    cost: { stone: 20 },
    buildTicks: 22,
    footprint: { w: 5, d: 5 },
    workers: 0,
    comfortRadius: 10,
    comfortValue: 8,
    requires: NO_REQUIREMENTS,
    unlockChapter: 4,
    description: 'Здесь собираются на праздники',
    shape: platform(5, 5, Material.PATH),
  },
  {
    id: 'garden',
    name: 'Сад',
    category: 'culture',
    cost: { plank: 6, fiber: 4 },
    buildTicks: 12,
    footprint: { w: 4, d: 4 },
    workers: 1,
    jobType: 'care',
    comfortRadius: 8,
    comfortValue: 7,
    requires: NO_REQUIREMENTS,
    unlockChapter: 2,
    description: 'Цветёт и пахнет',
    shape: platform(4, 4, Material.FLOWER_PINK),
  },
  {
    id: 'lookout',
    name: 'Смотровая площадка',
    category: 'culture',
    cost: { plank: 14, stone: 6 },
    buildTicks: 18,
    footprint: { w: 3, d: 3 },
    workers: 0,
    comfortRadius: 9,
    comfortValue: 8,
    requires: ['sawmill'],
    unlockChapter: 3,
    description: 'Отсюда видно весь остров',
    shape: [
      { x: 0, y: 0, z: 0, w: 1, h: 4, d: 1, mat: Material.WOOD },
      { x: 2, y: 0, z: 0, w: 1, h: 4, d: 1, mat: Material.WOOD },
      { x: 0, y: 0, z: 2, w: 1, h: 4, d: 1, mat: Material.WOOD },
      { x: 2, y: 0, z: 2, w: 1, h: 4, d: 1, mat: Material.WOOD },
      { x: 0, y: 4, z: 0, w: 3, h: 1, d: 3, mat: Material.PLANK },
    ],
  },
  {
    id: 'story_house',
    name: 'Дом историй',
    category: 'culture',
    cost: { plank: 20, glass: 4 },
    buildTicks: 26,
    footprint: { w: 4, d: 3 },
    workers: 0,
    comfortRadius: 8,
    comfortValue: 8,
    requires: ['glassworks'],
    unlockChapter: 4,
    description: 'Здесь хранят дневник острова',
    shape: hollowBox(4, 3, 3, Material.PLANK, Material.GLASS),
  },
  {
    id: 'music_stand',
    name: 'Музыкальный помост',
    category: 'culture',
    cost: { plank: 10 },
    buildTicks: 14,
    footprint: { w: 3, d: 3 },
    workers: 0,
    comfortRadius: 9,
    comfortValue: 7,
    requires: ['sawmill'],
    unlockChapter: 4,
    description: 'По вечерам отсюда слышно музыку',
    shape: platform(3, 3, Material.PLANK),
  },
  {
    id: 'bathing_place',
    name: 'Купальня',
    category: 'culture',
    cost: { plank: 12, stone: 8 },
    buildTicks: 18,
    footprint: { w: 3, d: 4 },
    workers: 0,
    comfortRadius: 8,
    comfortValue: 7,
    requires: ['sawmill'],
    unlockChapter: 4,
    description: 'Спуск к воде, где мелко и тепло',
    shape: platform(3, 4, Material.PLANK),
  },

  // Декор
  {
    id: 'flowerbed',
    name: 'Клумба',
    category: 'decor',
    cost: { fiber: 2 },
    buildTicks: 2,
    footprint: { w: 2, d: 2 },
    workers: 0,
    comfortRadius: 4,
    comfortValue: 3,
    requires: NO_REQUIREMENTS,
    unlockChapter: 1,
    description: 'Немного цвета под окном',
    shape: platform(2, 2, Material.FLOWER_AMBER),
  },
  {
    id: 'hedge',
    name: 'Живая изгородь',
    category: 'decor',
    cost: { fiber: 3 },
    buildTicks: 3,
    footprint: { w: 3, d: 1 },
    workers: 0,
    comfortRadius: 3,
    comfortValue: 2,
    requires: NO_REQUIREMENTS,
    unlockChapter: 2,
    description: 'Мягкая граница между дворами',
    shape: [{ x: 0, y: 0, z: 0, w: 3, h: 2, d: 1, mat: Material.LEAVES }],
  },
  {
    id: 'flagpole',
    name: 'Флагшток',
    category: 'decor',
    cost: { wood: 4, cloth: 1 },
    buildTicks: 4,
    footprint: { w: 1, d: 1 },
    workers: 0,
    comfortRadius: 5,
    comfortValue: 3,
    requires: ['loom'],
    unlockChapter: 3,
    description: 'Видно издалека',
    shape: [
      { x: 0, y: 0, z: 0, w: 1, h: 5, d: 1, mat: Material.WOOD },
      { x: 0, y: 4, z: 0, w: 1, h: 1, d: 1, mat: Material.FLOWER_PINK },
    ],
  },
  {
    id: 'stone_lantern',
    name: 'Каменный фонарик',
    category: 'decor',
    cost: { stone: 4 },
    buildTicks: 4,
    footprint: { w: 1, d: 1 },
    workers: 0,
    comfortRadius: 5,
    comfortValue: 3,
    requires: NO_REQUIREMENTS,
    unlockChapter: 2,
    description: 'Тёплая точка света у дорожки',
    shape: [
      { x: 0, y: 0, z: 0, w: 1, h: 2, d: 1, mat: Material.STONE },
      { x: 0, y: 2, z: 0, w: 1, h: 1, d: 1, mat: Material.GLASS },
    ],
  },
  {
    id: 'swing',
    name: 'Качели',
    category: 'decor',
    cost: { plank: 6, fiber: 2 },
    buildTicks: 6,
    footprint: { w: 2, d: 2 },
    workers: 0,
    comfortRadius: 6,
    comfortValue: 5,
    requires: ['sawmill'],
    unlockChapter: 2,
    description: 'Скрипят, но это приятный скрип',
    shape: [
      { x: 0, y: 0, z: 0, w: 1, h: 3, d: 1, mat: Material.WOOD },
      { x: 1, y: 0, z: 0, w: 1, h: 3, d: 1, mat: Material.WOOD },
      { x: 0, y: 3, z: 0, w: 2, h: 1, d: 1, mat: Material.PLANK },
    ],
  },
  {
    id: 'hammock',
    name: 'Гамак',
    category: 'decor',
    cost: { cloth: 2, wood: 2 },
    buildTicks: 4,
    footprint: { w: 3, d: 1 },
    workers: 0,
    comfortRadius: 5,
    comfortValue: 5,
    requires: ['loom'],
    unlockChapter: 3,
    description: 'Лучшее место для послеобеденного сна',
    shape: [
      { x: 0, y: 0, z: 0, w: 1, h: 2, d: 1, mat: Material.WOOD },
      { x: 2, y: 0, z: 0, w: 1, h: 2, d: 1, mat: Material.WOOD },
      { x: 0, y: 1, z: 0, w: 3, h: 1, d: 1, mat: Material.THATCH },
    ],
  },
];

const BY_ID = new Map(BUILDINGS.map((building) => [building.id, building]));

export function buildingType(id: string): BuildingType | undefined {
  return BY_ID.get(id);
}

/** Уровни производственных зданий (§6 ТЗ): улучшение на месте, а не новое здание. */
export const LEVEL_MULTIPLIER: Readonly<Record<1 | 2 | 3, number>> = { 1: 1, 2: 1.35, 3: 1.75 };

/** Черта характера, подходящая к работе. Даёт прибавку к производству (§5 ТЗ). */
export const JOB_TRAIT: Readonly<Record<JobType, string>> = {
  wood: 'hard_worker',
  stone: 'hard_worker',
  clay: 'tidy',
  sand: 'collector',
  fish: 'fisher',
  forage: 'collector',
  farm: 'gardener',
  craft: 'tidy',
  care: 'gardener',
};
